# Site settings
title: Code and Science
email: spowers.42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My journey through science, programming and making.  A collection of projects
  and thoughts as I explore these various interests.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: func-coder
github_username:  spowers42

# Build settings
markdown: kramdown
